---
title: "Mini-project 2"
sidebar: false
format: html
html-math-method: mathml
---

# Activity

**Purpose:** Create a graphical reference sheet/concept map that compactly shows as many concepts as possible from our Study Designs & Causal Inference unit.

**Task:** Work with your groups using whatever drawing tools you wish. Develop pictures and diagrams to graphically show the following. Try to use as little text as possible. (Icons can be helpful here!)

Suggestion: Proceed through the concepts in order. Make sure you understand and can explain the concept to each other. Add on to your graphical display to show the concept and update previous parts as needed to most effectively convey the concepts.

1. How is the design of a cohort study different from a case-control study?

2. Why would one choose to do a cohort study vs. a case-control study vs. a randomized experiment?
    - Compare the strengths and benefits in terms of ethical considerations, resources needed, ability to study rare diseases, ability to study rare exposures, ability to verify that exposure preceded the outcome, practical considerations for designing/running the study

3. In general, which of the following quantities can we estimate accurately in a cohort study? In a case-control study? (Note that we have only talked explicitly about some of these in either cohort or case-control studies. We're trying to fully connect the dots with this prompt.)
    - Incidence of disease in exposed, in unexposed
    - Prevalence of disease
    - Prevalence of exposure
    - Relative risk (RR)
    - Odds ratio (OR) (odds of disease in exposed / odds of disease in unexposed)
    - Odds ratio (OR) (odds of exposure in disease / odds of exposure non-diseased)

4. Concepts related to relative risk (RR), attributable risk (AR), and population attributable risk (PAR)
    - How can we interpret RR, AR, and PAR?
    - What is the difference between AR and PAR?
    - If a relative risk is high, is the risk of disease in the exposed high? What about the attributable risk in the exposed (AR)? What about the population attributable risk?

5. When is the odds ratio from a case-control study a good estimate of the relative risk that we would estimate from conducting a cohort study? (Why do we care about this?)

6. How can we use causal diagrams to understand what variables to stratify on (adjust for) in order to understand causal relationships between exposures and outcomes? Make sure to address confounders, mediators, and colliders in causal diagrams.
    - How do stratified association measures differ from overall association measures when confounding is present?

Put all group members' names at the top of your document. Submit this on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=90513) by the end of class.

**Requirements for passing:** Make a good faith effort at all tasks above. This activity will be graded for completion.

