---
title: "Project"
sidebar: false
---

# Goal

The goal of the project is to apply our course concepts to analyze a health or well-being topic of your choosing. I would like this project to be a **meaningful use of your time**, so I encourage you to **pick a health or well-being topic that is relevant to you**.


<br><br>


# Project requirements

## Team size

You can work alone or in groups of up to 3 for this project.

## Aligning with other classes

You may choose a project topic that is the same or similar to a topic that you're exploring in another course. This is encouraged! Combining multiple course perspectives can significantly increase the quality of your work.

## Format

You will create a blog post/web page that allows viewers to explore your health/well-being topic. This page should contain the following sections:

**Section 1:** Introduction and motivation

- **Purpose of this section:** Introduce the reader to the health/well-being topic that you're studying.
- **Details:**
    - Describe any biology, social science, and/or other background context that would help the reader understand what this area is.
    - Describe the importance of this condition in terms of relevant ideas from our **Measurement** unit: prevalence (burden), incidence (risk), life expectancy, survival.
    - Evaluate the accuracy and reliability of prevalence, incidence, life expectancy, and or survival data based on how these data were collected.
    - Include citations to all sources referenced as links in the text.

**Section 2:** Evaluation of published research

- **Purpose of this section:** Discuss what exposures, risk factors, and interventions researchers have studied with regards to your topic. Evaluate the methods and findings of published research.
- **Details:**
    - Each group member should find and evaluate one research article. This section should have one subsection per article.
    - In evaluating the **methods** of a research article:
        - Describe the study design used
        - Explain why this study design was used
        - Discuss limitations you saw or that the authors discussed in terms of study implementation (conduct of the study, measurement of variables)
        - Apply ideas from our **Study Designs** topic: observational studies, cohort studies, case-control studies, ecological studies, randomized experiments.
    - In evaluating the **findings** of a research article:
        - Summarize the main findings
        - Evaluate the ways in which the researchers interpret their statistical findings in the Results and Discussion sections of the article. Do the researchers interpret results accurately and draw reasonable conclusions?
        - Do the researchers adjust for an appropriate set of confounders in their analysis? Apply ideas from our **Causal Inference** topic: confounding, causation, causal diagrams
        - Make connections with ideas from our **Statistical Thinking** topic: logistic regression, sampling error and confidence intervals, type 1 and 2 errors, power, multiple testing, and biases

## Rubric

The rubric below details quality expectations for the different aspects of the project described in the Format section above.

Rubric category 1: Cited references

- **High pass:** Relevant and credible references are cited consistently throughout the blog post.
- **Pass:** Some sections of the blog post are missing relevant and credible references.
- **Needs Improvement:** Several sections of the blog post are missing relevant and credible references.

Rubric category 2: Writing quality

- **High pass:** Writing is clear, concise, and well-organized, with good flow from section to section.
- **Pass:** Writing is generally clear, concise, and well-organized but may sometimes warrant a different ordering to sentences or a reduction in repetition for better clarity.
- **Needs improvement:** Several sections of the writing are hard to follow.

Rubric category 3: Quality of content and connections to epidemiological concepts (Measurement topic)
Rubric category 4: Quality of content and connections to epidemiological concepts (Study Designs topic)
Rubric category 5: Quality of content and connections to epidemiological concepts (Causal Inference topic)
Rubric category 6: Quality of content and connections to epidemiological concepts (Statistical Thinking topic)

- **High pass:** Makes relevant connections to concepts from this unit (see Format section above for more details) and explains these connections clearly and accurately.
- **Pass:** Explanations of concepts from this unit are generally clear and accurate but have a few minor errors.
- **Needs improvement:** Several key relevant concepts are missing, and there are major errors in understanding of the included relevant concepts.


<br><br>


# Milestones

## Milestone 1

Due Monday, April 8 on [Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=91073) as a PDF. Only one student per team should submit this PDF.

**Goals:**

- Identify a health or well-being topic of interest
- Form project groups
- Think about an exposure or treatment that is relevant for the health or well-being topic for your project and start thinking about evidence for causal relationships between that exposure/treatment and outcomes.

**Task:** Provide responses to the following:

1. Confirm a health or well-being topic that you want to pursue. Identify up to 2 other students who are interested in the same topic. Come to a consensus about your topic.
    - **Provide team member names, and state your topic area.**

2. Refer to the [Format section](#format) above. **Write a draft of Section 1: Introduction and motivation.**

2. Identify an exposure or treatment related to your topic where the causal relationship between the exposure/treatment and health outcome is of interest. **Each team member should find one research article** relating in one of the following journals. If you aren't finding relevant results, you may need to find a different exposure/treatment. The following journals are good sources to start, but feel free to use [Google Scholar](https://scholar.google.com/) to find articles too. **Provide the title of the article and a link to the article.**
    - [American Journal of Epidemiology](https://academic.oup.com/aje)
    - [International Journal of Epidemiology](https://academic.oup.com/ije)
    - [Journal of the American Medical Association](https://jamanetwork.com/)
    - [New England Journal of Medicine](https://www.nejm.org/)
    
4. **For each article, provide a summary of the Methods section of the article.**
    - Describe the study design used
    - Explain why this study design was used
    - Discuss limitations you saw or that the authors discussed in terms of study implementation (conduct of the study, measurement of variables)
    - Apply ideas from our **Study Designs** topic: observational studies, cohort studies, case-control studies, ecological studies, randomized experiments.

5. [DAGitty](https://www.dagitty.net/) is an online tool for drawing causal diagrams. Navigate to the [DAGitty graphical interface](https://www.dagitty.net/dags.html) to begin sketching a causal diagram that depicts relationships between variables relevant to your topic.
    - You can add variables by clicking on the gray canvas and entering a variable name. Once you have a circle selected, you can indicate it as an exposure or outcome variable by clicking the checkboxes in the top left.
    - Add your exposure and outcome variables. They will be colored green and blue, respectively.
    - Add an arrow between the exposure and the outcome by first clicking the exposure circle and then the outcome circle.
    - Brainstorm with your team to come up with as many direct causes of the outcome as possible. Add these variables to your diagram and add arrows from these variables to the outcome.
    - Discuss with your team: do you think these variables are connected with the exposure/treatment? Add arrows (possibly with more variables) to represent these connections. **Take a screenshot of your causal diagram, and insert it into your document.**
    - Look in the top right for the text "Minimal sufficient adjustment sets for estimating the total effect of EXPOSURE on OUTCOME". The sets of variables listed for each bullet point are sufficient ones to adjust for to estimate the causal relationship between the exposure/treatment and outcome. **How do these sets of variables compare to what your research articles adjusted for? If there are discrepancies, discuss how feasible you think it would be to reconcile those differences in future studies.**

**Feedback:** This Milestone will be graded for completion. My aim is to give you feedback on Rubric categories 1 - 5.

## Final Submission

Task:

- Incorporate the instructor's feedback from Milestone 1.
- Add to your post to make connections with ideas from our **Statistical Thinking** topic. **Each team member** should address the following questions for their research article:
    - Summarize the findings of the article by interpreting the association measures presented (which could be odds ratios, relative risks) along with their 95% confidence intervals. If there are a lot of results reported, focus on interpreting 
    - Evaluate whether multiple testing might be an issue in the study.
    - Explain 1-2 biases that might be at play when looking at the study's results.

Logistics:

- Submit your work [on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=93874) by midnight on Monday, April 29. Only one team member per group needs to submit.
